name: Build and Release Ratflipper

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --onefile --windowed Ratflipper.py `
          --add-data "ratflipper.ico;." `
          --icon=ratflipper.ico `
          --name Ratflipper `
          --hidden-import=requests `
          --hidden-import=urllib3 `
          --hidden-import=idna `
          --hidden-import=charset_normalizer `
          --hidden-import=certifi

    - name: Move EXE to root
      run: move dist\\Ratflipper.exe Ratflipper.exe

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        name: Ratflipper ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        files: Ratflipper.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
