name: Build Windows Executable with PyInstaller

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if (Test-Path "requirements.txt") {
            pip install -r requirements.txt
          }
          pip install pyinstaller
        shell: pwsh

      - name: Build executable with icon
        run: |
          pyinstaller --onefile --windowed --icon=ratflipper.ico Ratflipper.py

      - name: Upload executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: Ratflipper-executable
          path: dist/Ratflipper.exe
